
default: help
.PHONY: default

help:
	@echo 'Usage:'
	@echo '	$$ make [action]'
	@echo
	@echo 'Example:'
	@echo '	$$ make'
	@echo '	$$ make help'
	@echo
	@echo '	$$ make keybind'
	@echo
.PHONY: help




keybind:
	./make-gnome-shell-keybind.sh
.PHONY: keybind
