
default: help
.PHONY: default

help:
	@echo 'Usage:'
	@echo '	$$ make [action]'
	@echo
	@echo 'Example:'
	@echo '	$$ make'
	@echo '	$$ make help'
	@echo
	@echo '	$$ make master-config'
	@echo
.PHONY: help




master-config:
	./make-gnome-shell-master.sh
.PHONY: master-config
