
default: help
.PHONY: default

help:
	@echo 'Usage:'
	@echo '	$$ make [action]'
	@echo
	@echo 'Example:'
	@echo '	$$ make'
	@echo '	$$ make help'
	@echo
	@echo '	$$ make tool-config'
	@echo
.PHONY: help




tool-config:
	./make-gnome-shell-tool.sh
.PHONY: tool-config
